version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - ${PORT_DB}:${PORT_DB}
    restart: unless-stopped
  app:
    build: .
    image: flask_lesson1
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    env_file:
      - .env
    depends_on:
      - database
    restart: unless-stopped
volumes:
  database-data: